name: SCLogin
authors: [superckl, Fireblast709]
version: 0.1
main: org.sensationcraft.login.SCLogin
website: www.sensationcraft.info
commands:
  login:
    description: Login to your SCLogin account
    usage: /<command> <password>
    aliases: [l]
  logout:
    description: Logout from your SCLogin account
    usage: /<command>
  quit:
    description: Safe quit command, useful for evading combat loggers
    usage: /<command>
    aliases: [q]
  changepassword:
    description: Change the password of your SCLogin account
    usage: /<command> <old password> <new password> <confirm new password>
    aliases: [changepw,cpw]
  register:
    description: Register your SCLogin account
    usage: /<command> <password> <confirm password>
  sclogin:
    description: administration command for trusted staff
    usage: /<command> [subcommand]
  unregister:
    description: unregisters the account you are logged in with
    usage: /<command>
  safeguard:
    description: Adds another layer of security to your account
    usage: /<command> enable|disable