name: SCLogin
authors: [superckl, Fireblast709]
version: 0.1
main: org.sensationcraft.login.SCLogin
website: www.sensationcraft.info
commands:
  login:
    description: Login to your SCLogin account
    usage: /<command> <password>
    aliases: [l]
  register:
    description: Register your SCLogin account
    usage: /<command> <password> <confirm password>
  sclogin:
    description: administration command for trusted staff
    usage: /<command> [subcommand]